### PR TITLE
Use prop-types from npm module, not React

### PR DESCRIPTION
**Pull request by mihaiblaga89**

### CODE REVIEW

**Comment by codeslayer1** [comment]
Hi @mihaiblaga89 ,

Can you please specify the purpose of this pull request? What benefits will prop-types library serve instead of using the native React.Proptypes?

**Comment by mihaiblaga89** [comment]
Because it's deprecated.

screen shot 2017-09-20 at 12 45 22

**Comment by codeslayer1** [comment]
Oh. Saw this just now.

screen shot 2017-09-20 at 3 18 24 pm

Thanks. Will merge the pull request soon and update on Npm.

**Comment by mihaiblaga89** [comment]
Thanks. Good work with the module. As a quick question, you have scriptUrl argument, that takes an actual URL. Is there any way to give the ckeditor.js as a file? I tried require('../../[...]ckeditor.js') but it does not work. I would avoid to have ckeditor folder exposed to the world. Thanks

**Comment by codeslayer1** [comment]
I haven't tried loading a local file actually. I use load-script module to load external script(creditor.js in our case). Will have to check if it can load a local file URL. Will let you know by evening.

**Comment by codeslayer1** [comment]
I just checked, it won't be possible to load the script using a local url because eventually the script should be publicly accessible so that it can be loaded on client's end.

**Comment by mihaiblaga89** [comment]
Thanks. In theory it can be bundled by webpack or something, but I don't have the time to mess with it at the moment. It works as it is, if this will become a problem later on I'll jump in. Thanks again

**Comment by codeslayer1** [comment]
Yup. In case you use webpack or any other bundler, you can bundle it with your other files. But doing this in the library would be an overkill and would bloat an otherwise simple library. And Thanks for contributing. 

In case you are interested in tech related discussions, you can join my group here on slack - https://goo.gl/QGyfyC

**Pull request merged**
