### PR TITLE
update ckeditor when prop changes

### PR DESCRIPTION
**Pull request by themre**
this PR updates ckeditor when props change. now it wasn't working if editor was visible and `content` prop changed.

### CODE REVIEW

**Comment by benfang928** [comment]
That is really useful and needed.

**Comment by L-Luciano** [comment]
Any news ?

**Comment by codeslayer1** [comment]
This is now merged and made live in version 1.1.0. You can get the latest version from NPM. 

Thanks for the PR @themre

**Comment by abumalick** [comment]
pushed a PR related to this one: https://github.com/codeslayer1/react-ckeditor/pull/58

**Pull request merged**
